name: portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: 
  carousel_slider_plus: ^7.0.1
  flutter_svg: ^2.0.10+1
  flutter_inset_box_shadow: ^1.0.7
  timeline_tile: ^2.0.0
  infinite_carousel: ^1.1.1
  url_launcher: ^6.1.12
  emailjs: ^4.0.0
  provider:
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/memoji.png
    - assets/icons/
    - assets/icons/skills_icons/
    - assets/images/
    - assets/images/certficate_icons/
    - assets/images/certficate_icons/hackerrank.png
    - assets/images/certficate_icons/mysql.png
    - assets/images/certficate_icons/python.png
    - assets/images/projects/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
